config/routes.rb
CustomerEnv::Application.routes.draw do
  root :to => "customers#new"

  resources :sessions
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  resources :users
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  resources :customers
  match 'submitted' => 'customers#submitted', :as => :customer_submitted
  match 'customer_search' => 'customers#index', :as => :customer_search

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :browser, :browser_version, :cookies, :email, :engine, :engine_version, :ip_address, :name, :operating_system, :raw_request, :searchable

  validates_presence_of :email, :name
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i

  before_save :set_searchable

  def self.search(search)
    if search
      where('searchable LIKE ?', "%#{search}%")
    else
      scoped
    end
  end

  private

  def set_searchable
    self.searchable = "#{self.name} #{self.email}".downcase
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation

  attr_accessor :password
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ControllerAuthentication
  protect_from_forgery
end

app/controllers/customers_controller.rb
require 'will_paginate/array'

class CustomersController < ApplicationController
  include ControllerAuthentication

  before_filter :login_required, :except => [:new, :create, :index, :submitted]

  # GET /customers
  # GET /customers.json
  def index
    # manual authorisation to allow customers to reach
    # /customers via post in create method
    redirect_to root_path and return unless current_user

    @customers = Customer.search(params[:search]).order("created_at DESC").paginate(:per_page => 10, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html
      format.json { render json: @customer }
    end
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    RequestParser.parse request do |ip_address, agent, cookies, raw_request|
      @customer.ip_address        = ip_address
      @customer.browser           = agent.name
      @customer.browser_version   = agent.version
      @customer.engine            = agent.engine
      @customer.engine_version    = agent.engine_version
      @customer.operating_system  = agent.os
      @customer.cookies           = cookies
      @customer.raw_request       = raw_request
    end

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customer_submitted_path }
      else
        format.html { render action: "new" }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end

  def submitted
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:login], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to_target_or_default customer_search_path, :notice => "Logged in successfully."
    else
      flash.now[:alert] = "Invalid login or password."
      render :action => 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "You have been logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required #, :except => [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Thank you for signing up! You are now logged in."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Your profile has been updated."
    else
      render :action => 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer, :html => { :class => 'form-horizontal' } do |f| %>
  <%= render "shared/error_messages", :target => @customer %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit 'Submit information', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/customers/index.html.erb
<%- model_class = Customer.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>

<%= form_tag customers_path, :method => 'get', :id => "customers_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil, :class => "btn" %>
  </p>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%=l customer.created_at %></td>
        <td>
          <%= link_to 'View details',
                      customer_path(customer), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      customer_path(customer),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @customers %>

app/views/customers/new.html.erb
<%- model_class = @customer.class -%>

<p>Please ensure you are submitting this request from the computer or device that is exhibiting the issue in question.</p>

<%= render :partial => 'form' %>

app/views/customers/show.html.erb
<%- model_class = @customer.class -%>
<h1><%= @customer.name %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:email) %>:</strong><br>
  <%= @customer.email %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:ip_address) %>:</strong><br>
  <%= @customer.ip_address %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:browser) %>:</strong><br>
  <%= @customer.browser %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:browser_version) %>:</strong><br>
  <%= @customer.browser_version %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:engine) %>:</strong><br>
  <%= @customer.engine %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:engine_version) %>:</strong><br>
  <%= @customer.engine_version %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:operating_system) %>:</strong><br>
  <%= @customer.operating_system %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:cookies) %>:</strong><br>
  <ul>
    <% @customer.cookies.split(';').each do |c| %>
      <% k, v = c.split ':' %>
      <li>
        <span class="cookie_name"><%= k %></span><br/>
        <span class="cookie_value"><%= v %></span>
    <% end %>
  </ul>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              customers_path, :class => 'btn'  %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              customer_path(@customer),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/customers/submitted.erb
<h1>Thank you</h1>
<p>
    We have received your information and will respond to your query as soon as possible
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music Glue Customer Diagnostics</title>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= yield(:head) %>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <% if current_user %>
            <%= link_to "Music Glue Customer Diagnostics", customers_path, :class => 'brand' %>
          <% else %>
            <%= link_to "Music Glue Customer Diagnostics", root_path, :class => 'brand' %>
          <% end %>
          <div class="nav-collapse">
            <ul class="nav pull-right">
              <% if current_user %>
                <li>
                  <%= link_to "log out", logout_path %>
                </li>
              <% else %>
                <li>
                  <%= link_to "admin log in", login_path %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="span9">
          <%= content_tag :h1, yield(:title) if show_title? %>
          <% flash.each do |name, msg| %>
            <%= content_tag :div, msg, :id => "flash_#{name}", :class => 'alert' %>
          <% end %>
          <%= yield %>
        </div>
        <div class="span3">
          <% if current_user %>
            <p>Logged in as <%= current_user.email %>.</p>
            <p><%= link_to "Edit my profile", edit_current_user_path %></p>
          <% else %>
            <h2>About</h2>
            <p>
                By submitting the below to the left, Music Glue will recieve information about environment to help us with your query. The data we will collect shall be:
            </p>
            <ul>
              <li>IP Address</li>
              <li>Browser</li>
              <li>Operating system</li>
              <li>Cookies (Music Glue sites only)</li>
            </ul>
            <p class="logo">
              <a href="http://www.musicglue.com/" target="_blank">
                <%= image_tag 'musicglue.jpg' %>
              </a>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
<div class="error_explanation alert alert-error">
  Sorry, your request could not be submitted because:
  <ul>
  <% target.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit (@user.new_record? ? "Sign up" : "Update"), :class => "btn" %></p>
<% end %>

app/views/users/edit.html.erb
<% title "Update Profile" %>

<%= render 'form' %>

app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>